# Use DinD
image: docker
services:
- docker:dind

# Stages
stages:
  - lint
  - build

# Login to Dockerhub
before_script:
  - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"

# Lint the Dockerfile using Hadolint
lint-the-dockerfile:
  stage: lint
  script:
    - docker pull hadolint/hadolint
    - docker run hadolint/hadolint hadolint --version
    - >
      docker run -i
      hadolint/hadolint hadolint
      - < Dockerfile

# Lint the README using markdownlint
lint-the-readme:
  stage: lint
  allow_failure: false
  script:
    - docker pull mivok/markdownlint
    - docker run mivok/markdownlint --version
    - >
      docker run -i
      mivok/markdownlint
      --rules ~MD013
      - < README.md

# Build and push to Dockerhub
build-and-push-the-thing:
  stage: build
  script:
    - docker build --pull --tag "$DOCKERHUB_IMAGE" .
    - docker push "$DOCKERHUB_IMAGE"
